server:
  port: 8006

spring:
  application:
    name: consul-consumer-service


  cloud:
    consul:
      host: 10.211.55.5
      port: 8500
      discovery:
        service-name: ${spring.application.name}